#!/usr/bin/env node
// Extract a recommended distiller config from the user's openclaw.json and
// emit it as a systemd EnvironmentFile.
//
// We prefer routing distillation through z.ai (anthropic-proxy-6 in a stock
// openclaw config) so the skillbank doesn't share a rate-limit bucket with
// the user's live agent (which usually runs through claude-code-plugin).
//
// Usage:
//   node scripts/extract-config.mjs            # prints to stdout
//   node scripts/extract-config.mjs --write    # writes to ~/.config/openclaw-skillbank.env
//
// Env overrides:
//   OPENCLAW_CONFIG  path to openclaw.json (default ~/.openclaw/openclaw.json)
//   PREFER_PROVIDER  comma-separated provider ids to try in order
//                    (default: anthropic-proxy-6,anthropic-proxy-4,anthropic-proxy-1)
//   PREFER_MODEL     comma-separated model ids to try in order
//                    (default: glm-5,glm-4.7,glm-5.1,claude-sonnet-4-6,claude-opus-4-6)

import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const HOME = os.homedir();
const CONFIG_PATH = process.env.OPENCLAW_CONFIG || path.join(HOME, ".openclaw/openclaw.json");
const PREFER_PROVIDER = (process.env.PREFER_PROVIDER || "anthropic-proxy-6,anthropic-proxy-4,anthropic-proxy-1").split(",");
const PREFER_MODEL = (process.env.PREFER_MODEL || "glm-5,glm-4.7,glm-5.1,claude-sonnet-4-6,claude-opus-4-6").split(",");
const OUT_PATH = path.join(HOME, ".config/openclaw-skillbank.env");
const WRITE = process.argv.includes("--write");

function parseJsonc(raw) {
  const stripped = raw.split("\n").map((line) => {
    let inStr = false, esc = false;
    for (let i = 0; i < line.length; i++) {
      const c = line[i];
      if (esc) { esc = false; continue; }
      if (c === "\\") { esc = true; continue; }
      if (c === '"') inStr = !inStr;
      if (!inStr && c === "/" && line[i + 1] === "/") return line.slice(0, i);
    }
    return line;
  }).join("\n").replace(/,(\s*[}\]])/g, "$1");
  return JSON.parse(stripped);
}

if (!fs.existsSync(CONFIG_PATH)) {
  console.error(`extract-config: ${CONFIG_PATH} not found`);
  process.exit(1);
}
const cfg = parseJsonc(fs.readFileSync(CONFIG_PATH, "utf8"));
const providers = cfg.models?.providers ?? {};

let chosenProvider = null;
let chosenModel = null;
for (const pid of PREFER_PROVIDER) {
  const p = providers[pid];
  if (!p || !p.baseUrl || !p.apiKey) continue;
  const ids = (p.models ?? []).map((m) => m.id);
  for (const mid of PREFER_MODEL) {
    if (ids.includes(mid)) {
      chosenProvider = { id: pid, baseUrl: p.baseUrl, apiKey: p.apiKey, api: p.api ?? "anthropic-messages" };
      chosenModel = mid;
      break;
    }
  }
  if (chosenProvider) break;
}

if (!chosenProvider) {
  console.error(`extract-config: no provider in PREFER_PROVIDER (${PREFER_PROVIDER.join(",")}) hosted any model in PREFER_MODEL`);
  process.exit(2);
}

const isAnthropic = chosenProvider.api === "anthropic-messages" || chosenProvider.baseUrl.includes("anthropic");
const lines = [
  `# openclaw-skillbank — generated by scripts/extract-config.mjs`,
  `# Source: ${CONFIG_PATH}`,
  `# Provider chosen: ${chosenProvider.id} (model ${chosenModel}, api=${isAnthropic ? "anthropic" : "openai"})`,
  `SKILLBANK_API_URL=${chosenProvider.baseUrl}`,
  `SKILLBANK_API_KEY=${chosenProvider.apiKey}`,
  `SKILLBANK_API_FORMAT=${isAnthropic ? "anthropic" : "openai"}`,
  `SKILLBANK_MODEL=${chosenModel}`,
  // Disable the busy-guard probe: routing through z.ai means the local
  // claude-code-plugin's inflight is irrelevant for skillbank's own load.
  `SKILLBANK_BUSY_GUARD_URL=`,
  ``,
];
const out = lines.join("\n");

if (WRITE) {
  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, out, { mode: 0o600 });
  console.error(`wrote ${OUT_PATH}`);
} else {
  process.stdout.write(out);
}
